s = 1749936248;
sec = s % 60;
m = (s - sec) / 60;
min = m % 60;
h = (m - min) / 60;
hour = h % 24;
d = (h - hour) / 24;
day = d % 7;
week = (d - day) / 7;
document.write(week + " weeks " + day + " days " + hour + " hours " + min + " minutes " + sec + " seconds");
